protected/models/Diagnosis.php
<?php

/**
 * This is the model class for table "{{diagnosis}}".
 *
 * The followings are the available columns in table '{{diagnosis}}':
 * @property integer $diag_id
 * @property string $diag_name
 * @property string $diag_status
 */
class Diagnosis extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{diagnosis}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('diag_name', 'required'),
             array('diag_name', 'unique'),
			array('diag_name', 'length', 'max'=>255),
			array('diag_catid', 'numerical', 'integerOnly'=>true),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('diag_id, diag_name,diag_catid, diag_status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'cmpCat' => array(self::BELONGS_TO, 'DiagnosisCategory', 'diag_catid'),
		);
	}
	
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'diag_id' => 'Diag',
			'diag_catid' => 'Category',
			'diag_name' => 'Name',
			'diag_status' => 'Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('diag_id',$this->diag_id);
		$criteria->compare('diag_catid',$this->diag_catid);
		$criteria->compare('diag_name',$this->diag_name,true);
		$criteria->compare('diag_status',$this->diag_status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
            'sort' => array(
                'defaultOrder' => 'diag_id DESC',
            )
		));
	}


    public function getDiagnosisCategory(){
        return CHtml::listData(DiagnosisCategory::model()->findAllByAttributes(array('dia_catstatus' => '1')), 'dia_catid', 'dia_catname');
    }

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Diagnosis the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}


    public function displayStatus() {

        if ($this->diag_status == '1')
           $img = '<img src="' . Yii::app()->theme->baseUrl . '/img/active.png" title="Active"/>';
       else
           $img = '<img src="' . Yii::app()->theme->baseUrl . '/img/inactive.png" title="Inactive"/>';


       return CHtml::link(
           $img, '', array(
           'onClick' => 'changestatus("Diagnosis" , '.$this->diag_id.')',
           'style' => "cursor:pointer;"
           )
       );

    }



}

protected/controllers/DiagnosisController.php
<?php

class DiagnosisController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('create', 'update', 'admin', 'delete', 'ChangeStatus', 'Inlineedit'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('admin', 'delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

    public function actionChangeStatus($id) {
        
        $model = $this->loadModel($id);
        
        if ($model->diag_status == '1') {
            $status = '0';
        } else {
            $status = '1';
        }
    
        $model->diag_status = $status;

        $model->saveAttributes(array('diag_status'));

        Yii::app()->end();
    }


	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Diagnosis;

		// Uncomment the following line if AJAX validation is needed
		 $this->performAjaxValidation($model);

        if (isset($_POST['Diagnosis'])) {
            $model->attributes = $_POST['Diagnosis'];
            if ($model->save()) {
                Yii::app()->user->setFlash('success', '<strong>Well done!</strong> Diagnosis has been created successfully.');
                if (Yii::app()->request->isAjaxRequest) {
                    $msg = '';
                    foreach (Yii::app()->user->getFlashes() as $key => $message) {
                        $msg.= '<div class="alert alert-' . $key . '">'
                                . '<button type="button" class="close" data-dismiss="alert">×</button>'
                                . $message . "</div>\n";
                    }
                    echo CJSON::encode(array(
                        'success' => true,
                        'div' => $msg
                    ));
                    exit;
                }
                Yii::app()->end();
                #$this->redirect(array('/discipline/admin'));
            } else {
                $error = CActiveForm::validate($model);
                if ($error != '[]')
                    echo $error;
                Yii::app()->end();
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
		
	}

    public function actionInlineedit() {

        $es = new EditableSaver('Diagnosis');
        try {
            $es->update();
        } catch (CException $e) {
            echo CJSON::encode(array('success' => false, 'msg' => $e->getMessage()));
            return;
        }
        echo CJSON::encode(array('success' => true));
    }

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Diagnosis']))
		{
			$model->attributes=$_POST['Diagnosis'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->diag_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Diagnosis');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Diagnosis('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Diagnosis']))
			$model->attributes=$_GET['Diagnosis'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Diagnosis the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Diagnosis::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Diagnosis $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='diagnosis-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/diagnosis/_form.php
<?php
/* @var $this DiagnosisController */
/* @var $model Diagnosis */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'diagnosis-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation' => true,
    'clientOptions' => array(
        'validateOnSubmit' => true,
    //  'afterSubmit'=>'js:yiiFix.ajaxSubmit.afterValidate'
    )
        ));
?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>
    <?php // echo $form->errorSummary($model); ?>


	<div class="row">

		<div class="form-group col-lg-3 clear">  
			<?php echo $form->labelEx($model,'diag_name'); ?>
			<?php echo $form->textField($model,'diag_name',array('size'=>60,'maxlength'=>255, 'class' => 'form-control')); ?>
			<?php echo $form->error($model,'diag_name'); ?>
		</div>
 
    <div class="form-group col-lg-3 clear">
        <?php echo $form->labelEx($model,'diag_catid'); ?> 
        <?php echo $form->dropDownList($model, 'diag_catid', $model->getDiagnosisCategory(), array('class' => 'form-control' , 'empty'=>'--Select Category--')); ?>           
        <?php echo $form->error($model,'diag_catid'); ?>
    </div> 

		<div class="form-group col-lg-3 clear">  
		<?php echo $form->labelEx($model,'diag_status'); ?>
		<?php echo $form->dropDownList($model, 'diag_status', array('1' => 'Active', '0' => 'In-Active'), array('class' => 'form-control')); ?>
		<?php echo $form->error($model,'diag_status'); ?>
		</div>
        <div class="buttons form-group col-lg-3 searchbutton">
		 <?php //echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class' => 'btn btn-primary')); ?> 
            <?php
        //  FB::setEnabled('false');
        //  echo  CHtml::submitButton($model->isNewRecord ? 'Submit' : 'Save');

        echo CHtml::ajaxSubmitButton($model->isNewRecord ? 'Submit' : 'Save', $this->createUrl('diagnosis/create'), array('type' => 'POST',
            'success' => 'function(data) {
                                
                             var response= jQuery.parseJSON(data);

                             if (response.success ==true){
                             //alert(response.div);
                             $("#statusMsg").html("");
                             $("#statusMsg").append(response.div);
                             $("#statusMsg").show().delay(3000).hide(0);
                             $("#diagnosis-form")[0].reset();
                             update_grid_view();
                             return false;
                             }else{
                                data = JSON.parse(data);
                                      $.each(data, function(key, val) {
                        $("#diagnosis-form #"+key+"_em_").text(val);                                                    
                        $("#diagnosis-form #"+key+"_em_").show();
                        });     
                                 }

                             }' //success
                ), array('type' => 'submit', 'class' => 'btn btn-primary')
        );
        ?>

        </div>
    </div> 
    <?php $this->endWidget(); ?>
</div><!-- form -->

protected/views/diagnosis/_search.php
<?php
/* @var $this DiagnosisController */
/* @var $model Diagnosis */
/* @var $form CActiveForm */
?>

<div class="wide form">

	<?php $form=$this->beginWidget('CActiveForm', array(
		'action'=>Yii::app()->createUrl($this->route),
		'method'=>'get',
	)); ?>

	<div class="form-group col-lg-3"> 
		<?php echo $form->label($model,'diag_name'); ?>
		<?php echo $form->textField($model,'diag_name',array('size'=>60,'maxlength'=>255,'class' => 'form-control')); ?>
	</div>

	<div class="form-group col-lg-3">
		<?php echo $form->label($model,'diag_status'); ?>
		<?php echo $form->dropDownList($model, 'diag_status', array('1' => 'Active', '0' => 'In-Active'), array('class' => 'form-control' ,'empty' =>'All' )); ?>
	</div>

    <div class="row buttons form-group">        
        <?php echo CHtml::submitButton('Search' , array('class'=>'btn btn-primary searchbutton')); ?>
    </div>

	<?php $this->endWidget(); ?>
	
</div><!-- search-form -->

protected/views/diagnosis/admin.php
<?php
/* @var $this DiagnosisController */
/* @var $model Diagnosis */

$this->breadcrumbs=array(
	'Diagnosis'=>array('admin'),
	'Manage Diagnosis',
);

$this->menu=array(
	array('label'=>'List Diagnosis', 'url'=>array('admin')),
	array('label'=>'Create Diagnosis', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-f').toggle();
	return false;
});
$('.search-f form').submit(function(){
	$('#diagnosis-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
function update_grid_view()
{
	$('#diagnosis-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
}
");
?>
<div id="statusMsg">   

<?php
    foreach (Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="alert alert-' . $key . '">'
        . '<button type="button" class="close" data-dismiss="alert">×</button>'
        . $message . "</div>\n";
    }
    ?>    
</div>
<?php
Yii::app()->clientScript->registerScript(
        'flashMassageEffect', '$("#statusMsg").animate({opacity: 1.0}, ' . Yii::app()->params["flasMsgTimeOut"] . ').fadeOut("slow");', CClientScript::POS_READY
);
?>
<div class="row">
 
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

    <div class="col-md-12">
        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Search</h4>
                <div class="panel-control">
                    <a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="" class="panel-collapse" data-original-title="Expand/Collapse"><i class="icon-arrow-down"></i></a>
                </div>
            </div>
            <div class="panel-body" style="display: none;">
                <div class="search-f">
                    <?php
                    $this->renderPartial('_search', array(
                        'model' => $model,
                    ));
                    ?>
                </div>  
            </div>

        </div>
    </div><!-- search-form -->
    <div class="col-md-12">

        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Diagnosis</h4>
                <div class="panel-control">
                    <a href="#" class="btn btn-success btn btn-primary add_button" ><i class="fa fa-plus"></i> Add Diagnosis </a>
                </div>
            </div>
            <div class="panel-body">
                <div class="add_form" style="display: none;">
                    <?php
                    $this->renderPartial('_form', array(
                        'model' => $model,
                    ));
                    ?>
                </div> 
                <div class="table-responsive">
                    <?php
                    $this->widget('zii.widgets.grid.CGridView', array(
                        'id' => 'diagnosis-grid',
                        'dataProvider' => $model->search(),
                        'itemsCssClass' => 'table table-hover table-striped',
                        'template' => "{items}\n{summary}{pager}",
                        //'filter' => $model,
                        'columns' => array(
                           
                            array(
                                'class' => 'editable.EditableColumn',
                                'name' => 'diag_name',
                                'headerHtmlOptions' => array('style' => 'width: 30%'),
                                'editable' => array(//editable section
                                    //   'apply'      => '$data->user_status != 4', //can't edit deleted users
                                    'url' => $this->createUrl('diagnosis/inlineedit'),
                                    'placement' => 'right',
                                    'mode' => 'inline'
                                ) 
                            ),
                            array(
                                'class' => 'editable.EditableColumn',
                               'name' => 'diag_catid',
                              // 'value' => '$data->brndVacine->brnd_name', 
                                'htmlOptions' => array('width' => '30%', 'style' => 'text-align:center;'),
                                'headerHtmlOptions' => array('width' => '30%', 'style' => 'text-align:center;'),
                                'editable' => array(//editable section
                                    //   'apply'      => '$data->user_status != 4', //can't edit deleted users
                                     'type'     => 'select',
                                    'url' => $this->createUrl('diagnosis/inlineedit'),
                                    'placement' => 'right',

                                    'mode' => 'inline',
                                    'source'    => $model->getDiagnosisCategory(),
                                )
                           ), 
                            array(
                                'name' => 'diag_status',
                                'value' => '$data->displayStatus()',
                                'type' => 'raw',
                                'htmlOptions' => array('width' => '20%', 'style' => 'text-align:center;'),
                                'headerHtmlOptions' => array('width' => '20%', 'style' => 'text-align:center;'),
                            ),
                            array(
                                'header' => 'Actions',
                                'class' => 'CButtonColumn',
                                'template' => '{delete}',
                                'htmlOptions' => array('width' => '20%','text-align' => 'left'),
                                'headerHtmlOptions' => array('width' => '20%', 'style' => 'text-align:left;'),
                                'deleteConfirmation' => Yii::t('warnings', 'Are you sure you want to delete this Diagnosis?'),
                                'afterDelete' => 'function(link,success,data){$("#statusMsg").html(data).show();}',
                                'buttons' => array( 
                                    'delete' => array(
                                        'label' => Yii::t('common', '<i class="fa fa-remove"></i>'),
                                        'url' => 'Yii::app()->createUrl("/diagnosis/delete",array("id"=>$data["diag_id"]))',
                                        'options' => array('class' => 'btn btn-danger', 'title' => 'Delete'),
                                        'imageUrl' => false,
                                    ),
                                ),
                            ),
                        ),
                    ));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div> 

protected/views/diagnosis/create.php
<?php
/* @var $this DiagnosisController */
/* @var $model Diagnosis */

$this->breadcrumbs=array(
	'Diagnosises'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Diagnosis', 'url'=>array('index')),
	array('label'=>'Manage Diagnosis', 'url'=>array('admin')),
);
?>

<h1>Create Diagnosis</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/diagnosis/index.php
<?php
/* @var $this DiagnosisController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Diagnosises',
);

$this->menu=array(
	array('label'=>'Create Diagnosis', 'url'=>array('create')),
	array('label'=>'Manage Diagnosis', 'url'=>array('admin')),
);
?>

<h1>Diagnosises</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/diagnosis/update.php
<?php
/* @var $this DiagnosisController */
/* @var $model Diagnosis */

$this->breadcrumbs=array(
	'Diagnosises'=>array('index'),
	$model->diag_id=>array('view','id'=>$model->diag_id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Diagnosis', 'url'=>array('index')),
	array('label'=>'Create Diagnosis', 'url'=>array('create')),
	array('label'=>'View Diagnosis', 'url'=>array('view', 'id'=>$model->diag_id)),
	array('label'=>'Manage Diagnosis', 'url'=>array('admin')),
);
?>

<h1>Update Diagnosis <?php echo $model->diag_id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>