protected/models/Frequency.php
<?php

/**
 * This is the model class for table "{{frequency}}".
 *
 * The followings are the available columns in table '{{frequency}}':
 * @property integer $frqcy_id
 * @property string $frqcy_name
 * @property string $frqcy_status
 */
class Frequency extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{frequency}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('frqcy_name', 'required'),
                        array('frqcy_name', 'unique'),
			array('frqcy_name', 'length', 'max'=>255),
			array('frqcy_status', 'length', 'max'=>1),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('frqcy_id, frqcy_name, frqcy_status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'frqcy_id' => 'Frqcy',
			'frqcy_name' => 'Name',
			'frqcy_status' => 'Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('frqcy_id',$this->frqcy_id);
		$criteria->compare('frqcy_name',$this->frqcy_name,true);
		$criteria->compare('frqcy_status',$this->frqcy_status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
            'sort' => array(
                'defaultOrder' => 'frqcy_id DESC',
            )
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Frequency the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}


    public function displayStatus() {

	    if ($this->frqcy_status == '1')
	        $img = '<img src="' . Yii::app()->theme->baseUrl . '/img/active.png" title="Active"/>';
	    else
	        $img = '<img src="' . Yii::app()->theme->baseUrl . '/img/inactive.png" title="Inactive"/>';


       return CHtml::link(
                       $img, '', array(
                       'onClick' => 'changestatus("frequency" , '.$this->frqcy_id.')',
                       'style' => "cursor:pointer;"
                       )
       );
	}

}

protected/controllers/FrequencyController.php
<?php

class FrequencyController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'admin', 'delete', 'ChangeStatus', 'Inlineedit'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array(),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionChangeStatus($id) {
        $model = $this->loadModel($id);

        if ($model->frqcy_status == '1') {
            $status = '0';
        } else {
            $status = '1';
        }

        $model->frqcy_status = $status;

        $model->saveAttributes(array('frqcy_status'));

        Yii::app()->end();
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Frequency;

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if (isset($_POST['Frequency'])) {
            $model->attributes = $_POST['Frequency'];

            if ($model->save()) {
                Yii::app()->user->setFlash('success', '<strong>Well done!</strong> Frequency has been created successfully.');

                if (Yii::app()->request->isAjaxRequest) {
                    $msg = '';
                    foreach (Yii::app()->user->getFlashes() as $key => $message) {
                        $msg.= '<div class="alert alert-' . $key . '">'
                                . '<button type="button" class="close" data-dismiss="alert">×</button>'
                                . $message . "</div>\n";
                    }
                    echo CJSON::encode(array(
                        'success' => true,
                        'div' => $msg
                    ));
                    exit;
                }
                Yii::app()->end();

                //$this->redirect(array('/frequency/admin'));
            } else {
                $error = CActiveForm::validate($model);
                if ($error != '[]')
                    echo $error;
                Yii::app()->end();
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionInlineedit() {

        $es = new EditableSaver('Frequency');
        try {
            $es->update();
        } catch (CException $e) {
            echo CJSON::encode(array('success' => false, 'msg' => $e->getMessage()));
            return;
        }
        echo CJSON::encode(array('success' => true));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Frequency'])) {
            $model->attributes = $_POST['Frequency'];
            if ($model->save()) {
                Yii::app()->user->setFlash('success', '<strong>Well done!</strong> Frequency has been updated successfully.');
                $this->redirect(array('/frequency/admin'));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {

        $result = $this->loadModel($id)->delete();

        if ($result) {
            Yii::app()->user->setFlash('success', '<strong>Great!</strong> Frequency has been deleted successfully.');
        } else
            Yii::app()->user->setFlash('error', '<strong>Oh snap!</strong> Frequency has been not deleted successfully');

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax'])) {
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else {
            foreach (Yii::app()->user->getFlashes() as $key => $message) {
                echo '<div class="alert alert-' . $key . '">'
                . '<button type="button" class="close" data-dismiss="alert">×</button>'
                . $message . "</div>\n";
            }
        }
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Frequency');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Frequency('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Frequency']))
            $model->attributes = $_GET['Frequency'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Frequency the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Frequency::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Frequency $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'frequency-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/frequency/_form.php
<?php
/* @var $this FrequencyController */
/* @var $model Frequency */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'frequency-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        //  'afterSubmit'=>'js:yiiFix.ajaxSubmit.afterValidate'
        )
    ));
    ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <?php //echo $form->errorSummary($model);  ?>

    <div class="row">
        <div class="form-group col-lg-4 clear">
            <?php echo $form->labelEx($model, 'frqcy_name'); ?>
            <?php echo $form->textField($model, 'frqcy_name', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <?php echo $form->error($model, 'frqcy_name'); ?>
        </div> 
        <div class="form-group col-lg-4 clear">
            <?php echo $form->labelEx($model, 'frqcy_status'); ?>
            <?php echo $form->dropDownList($model, 'frqcy_status', array('1' => 'Active', '0' => 'In-Active'), array('class' => 'form-control')); ?>
            <?php echo $form->error($model, 'frqcy_status'); ?>
        </div>
        <div class="buttons form-group col-lg-4 searchbutton">
            <?php //echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class' => 'btn btn-primary'));  ?>
            <!-- <a href="<?php echo Yii::app()->createUrl('/frequency/admin') ?>" class="btn btn-danger" >Cancel</a> -->

            <?php
            //  FB::setEnabled('false');
            //  echo  CHtml::submitButton($model->isNewRecord ? 'Submit' : 'Save');

            echo CHtml::ajaxSubmitButton($model->isNewRecord ? 'Submit' : 'Save', $this->createUrl('frequency/create'), array('type' => 'POST',
                'success' => 'function(data) {
                               //  alert(data);
                             var response= jQuery.parseJSON (data);

                             if (response.success ==true){
                             //alert(response.div);
                             $("#statusMsg").html("");
                             $("#statusMsg").append(response.div);
                             $("#statusMsg").show().delay(3000).hide(0);
                             $("#frequency-form")[0].reset();
                             update_grid_view();
                             return false;
                             }else{
//                             alert(data);
data = JSON.parse(data);
                                      $.each(data, function(key, val) {
                        $("#frequency-form #"+key+"_em_").text(val);                                                    
                        $("#frequency-form #"+key+"_em_").show();
                        });    
                                 }

                             }' //success
                    ), array('type' => 'submit', 'class' => 'btn btn-primary')
            );
            ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/frequency/_search.php
<?php
/* @var $this FrequencyController */
/* @var $model Frequency */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'action' => Yii::app()->createUrl($this->route),
        'method' => 'get',
    ));
    ?>

    <div class="form-group col-lg-3">
        <?php echo $form->label($model, 'frqcy_name'); ?>
        <?php echo $form->textField($model, 'frqcy_name', array('class' => 'form-control')); ?>
    </div>

    <div class="form-group col-lg-3">
        <?php echo $form->label($model, 'frqcy_status'); ?>
        <?php echo $form->dropDownList($model, 'frqcy_status', array('1' => 'Active', '0' => 'In-Active'), array('class' => 'form-control', 'empty' => 'All')); ?>
    </div>

    <div class="buttons form-group col-lg-3">
        <?php echo CHtml::submitButton('Search', array('class' => 'btn btn-primary searchbutton')); ?>
    </div>
    <?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/frequency/admin.php
<?php
/* @var $this FrequencyController */
/* @var $model Frequency */

$this->breadcrumbs=array(
	'Frequencies'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Frequency', 'url'=>array('index')),
	array('label'=>'Create Frequency', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-f form').submit(function(){
	$('#frequency-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});

function update_grid_view()
{
	$('#frequency-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
}

");
?>
<div id="statusMsg">    
    <?php
    foreach (Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="alert alert-' . $key . '">'
        . '<button type="button" class="close" data-dismiss="alert">×</button>'
        . $message . "</div>\n";
    }
    ?>    
</div>
<?php
Yii::app()->clientScript->registerScript(
        'flashMassageEffect', '$("#statusMsg").animate({opacity: 1.0}, ' . Yii::app()->params["flasMsgTimeOut"] . ').fadeOut("slow");', CClientScript::POS_READY
);
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Search</h4>
                <div class="panel-control">
                    <a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="" class="panel-collapse" data-original-title="Expand/Collapse"><i class="icon-arrow-down"></i></a>
                </div>
            </div>
            <div class="panel-body" style="display: none;">
                <div class="search-f">
                    <?php
                    $this->renderPartial('_search', array(
                        'model' => $model,
                    ));
                    ?>
                </div>  
            </div>

        </div>
    </div><!-- search-form -->

    <div class="col-md-12">

        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Frequencies </h4>
                <div class="panel-control">
                    <a href="javascript:void(0);" class="btn btn-success btn btn-primary add_button" ><i class="fa fa-plus"></i> Add Frequencies </a>
                </div>
			</div>

<div class="panel-body">
<div class="add_form" style="display: none;">
                    <?php
                    $this->renderPartial('_form', array(
                        'model' => $model,
                    ));
                    ?>
                </div>
                <div class="table-responsive">
                    <?php
                    $this->widget('zii.widgets.grid.CGridView', array(
                        'id' => 'frequency-grid',
                        'dataProvider' => $model->search(),
                        'itemsCssClass' => 'table table-hover table-striped',
                        'template' => "{items}\n{summary}{pager}",
                        //'filter' => $model,
                        'columns' => array(
                            // 'dis_id',
//                            array(
//                                'name' => 'frqcy_name',
//                                'htmlOptions' => array('width' => '70%'),
//                                'headerHtmlOptions' => array('width' => '70%'),
//                            ),
                            array(
                                'class' => 'editable.EditableColumn',
                                'name' => 'frqcy_name',
                                'headerHtmlOptions' => array('style' => 'width: 70%'),
                                'editable' => array(//editable section
                                    //   'apply'      => '$data->user_status != 4', //can't edit deleted users
                                    'url' => $this->createUrl('frequency/inlineedit'),
                                    'placement' => 'right',
                                    'mode' => 'inline'
                                )
                            ),
                            array(
                                'name' => 'frqcy_status',
                                'value' => '$data->displayStatus()',
                                'type' => 'raw',
                                'htmlOptions' => array('width' => '8%', 'style' => 'text-align:center;'),
                                'headerHtmlOptions' => array('width' => '8%', 'style' => 'text-align:center;'),
                            ),
                            array(
                                'header' => 'Actions',
                                'class' => 'CButtonColumn',
                                'template' => '{delete}',
                                'htmlOptions' => array('width' => '8%'),
                                'deleteConfirmation' => Yii::t('warnings', 'Are you sure you want to delete this Frequency?'),
                                'afterDelete' => 'function(link,success,data){$("#statusMsg").html(data).show();}',
                                'buttons' => array(
//                                    'edit' => array(
//                                        'label' => Yii::t('common', '<i class="fa fa-edit"></i> Edit'),
//                                        'url' => 'Yii::app()->createUrl("/frequency/update",array("id"=>$data["frqcy_id"]))',
//                                        'options' => array('class' => 'btn btn-primary', 'title' => 'Edit'),
//                                        'imageUrl' => false,
//                                    ),
                                    'delete' => array(
                                        'label' => Yii::t('common', '<i class="fa fa-remove"></i> Delete'),
                                        'url' => 'Yii::app()->createUrl("/frequency/delete",array("id"=>$data["frqcy_id"]))',
                                        'options' => array('class' => 'btn btn-danger', 'title' => 'Delete'),
                                        'imageUrl' => false,
                                    ),
                                ),
                            ),
                        ),
                    ));
                    ?>  
                </div>
            </div>

                </div>
            </div>

protected/views/frequency/create.php
<?php
/* @var $this FrequencyController */
/* @var $model Frequency */

$this->breadcrumbs=array(
	'Frequencies'=>array('index'),
	'Add',
);

$this->menu=array(
	array('label'=>'List Frequency', 'url'=>array('index')),
	array('label'=>'Manage Frequency', 'url'=>array('admin')),
);
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Add  Frequency</h4>
            </div>
            <div class="panel-body" >
                <?php $this->renderPartial('_form', array('model' => $model)); ?>
            </div>

        </div>
    </div><!-- search-form -->
</div> 

protected/views/frequency/index.php
<?php
/* @var $this FrequencyController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Frequencies',
);

$this->menu=array(
	array('label'=>'Create Frequency', 'url'=>array('create')),
	array('label'=>'Manage Frequency', 'url'=>array('admin')),
);
?>

<h1>Frequencies</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/frequency/update.php
<?php

/* @var $this FrequencyController */
/* @var $model Frequency */

$this->breadcrumbs=array(
	'Frequencies'=>array('index'),
	$model->frqcy_id=>array('view','id'=>$model->frqcy_id),
	'Update',
);

?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Edit Frequency</h4>
            </div>
            <div class="panel-body" >
                <?php $this->renderPartial('_form', array('model' => $model)); ?>
            </div>

        </div>
    </div><!-- search-form -->
</div>