protected/models/Facility.php
<?php

/**
 * This is the model class for table "{{facility}}".
 *
 * The followings are the available columns in table '{{facility}}':
 * @property integer $fac_id
 * @property integer $fac_usr_id
 * @property string $fac_name
 * @property string $fac_address
 * @property string $fac_city
 * @property string $fac_state
 * @property string $fac_zip_code
 * @property string $fac_country
 * @property string $fac_phone
 * @property string $fac_fax
 * @property string $fac_email
 * @property string $fac_website
 * @property string $fac_to_timing
 * @property string $fac_from_timing
 * @property string $fac_status
 */
class Facility extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{facility}}';
	}

        /**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
//			array('fac_usr_id, fac_name, fac_address, fac_city, fac_state, fac_zip_code, fac_country, fac_phone, fac_fax, fac_email, fac_website, fac_to_timing, fac_from_timing, fac_status', 'required'),
//			array('fac_usr_id', 'numerical', 'integerOnly'=>true),
//			array('fac_name, fac_city, fac_state, fac_country, fac_website', 'length', 'max'=>200),
//			array('fac_zip_code', 'length', 'max'=>10),
//			array('fac_phone, fac_fax', 'length', 'max'=>20),
//			array('fac_email, fac_to_timing, fac_from_timing', 'length', 'max'=>100),
//			array('fac_status', 'length', 'max'=>1),
//			
//			Create Facility rules
			array('fac_name', 'required' , 'on'=>'create'),
                        array('fac_name', 'checkname' ,'on'=>'create'),
                    
                        //Setup Facility
                        array('fac_name, fac_address, fac_city, fac_state, fac_zip_code, fac_country', 'required' , 'on'=>'setup'),
                        array('fac_name', 'unique' ,'on'=>'setup'),
                        
                        //Settings Facility
                        array('fac_name, fac_address, fac_city, fac_state, fac_zip_code, fac_country', 'required' , 'on'=>'settings'),
                        array('fac_phone, fac_fax, fac_website, fac_to_timing, fac_from_timing', 'safe' , 'on'=>'settings'),
                        array('fac_name', 'unique' ,'on'=>'settings'),
                    
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('fac_id, fac_usr_id, fac_name, fac_address, fac_city, fac_state, fac_zip_code, fac_country, fac_phone, fac_fax, fac_email, fac_website, fac_to_timing, fac_from_timing, fac_status', 'safe', 'on'=>'search'),
		);
	}
        
        public function checkname(){
            if(!empty($this->fac_name)){
                $count = $this->countByAttributes(array('fac_name'=> $this->fac_name , 'fac_usr_id'=>  Yii::app()->user->id));
                
                if($count != 0){
                    $this->addError('fac_name', 'Name "'.$this->fac_name.'" has already been taken.');
                }
            }
        }
        


	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}



    public function getCountryState(){
        return CHtml::listData(States::model()->findAllByAttributes(array('countryID'=>'IND')), 'stateID', 'stateName');
    }
 
    public function getStateCity($state_id = NULL){
    	if(empty($state_id)){
			return CHtml::listData(Cities::model()->findAllByAttributes(array()), 'cityID', 'cityName');
    	}
    	else{
    		return CHtml::listData(Cities::model()->findAllByAttributes(array('stateID'=>$state_id)), 'cityID', 'cityName');	
    	}
        
    }

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'fac_id' => 'Fac',
			'fac_usr_id' => 'Fac Usr',
			'fac_name' => 'Name',
			'fac_address' => 'Address',
			'fac_city' => 'City',
			'fac_state' => 'State',
			'fac_zip_code' => 'Zip Code',
			'fac_country' => 'Country',
			'fac_phone' => 'Phone',
			'fac_fax' => 'Fax',
			'fac_email' => 'Email',
			'fac_website' => 'Website',
			'fac_to_timing' => 'To Timing',
			'fac_from_timing' => 'From Timing',
			'fac_status' => 'Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('fac_id',$this->fac_id);
		$criteria->compare('fac_usr_id',  Yii::app()->user->id);
		$criteria->compare('fac_name',$this->fac_name,true);
		$criteria->compare('fac_address',$this->fac_address,true);
		$criteria->compare('fac_city',$this->fac_city,true);
		$criteria->compare('fac_state',$this->fac_state,true);
		$criteria->compare('fac_zip_code',$this->fac_zip_code,true);
		$criteria->compare('fac_country',$this->fac_country,true);
		$criteria->compare('fac_phone',$this->fac_phone,true);
		$criteria->compare('fac_fax',$this->fac_fax,true);
		$criteria->compare('fac_email',$this->fac_email,true);
		$criteria->compare('fac_website',$this->fac_website,true);
		$criteria->compare('fac_to_timing',$this->fac_to_timing,true);
		$criteria->compare('fac_from_timing',$this->fac_from_timing,true);
		$criteria->compare('fac_status',$this->fac_status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Facility the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
        

    public function displayStatus() {

        if ($this->fac_status == '1')
            $img = '<img src="' . Yii::app()->theme->baseUrl . '/img/active.png" title="Active"/>';
        else
            $img = '<img src="' . Yii::app()->theme->baseUrl . '/img/inactive.png" title="Inactive"/>';

       return CHtml::link(
                       $img, '', array(
                       'onClick' => 'changestatus("Facility" , '.$this->fac_id.')',
                       'style' => "cursor:pointer;"
                       )
       );
           }
}

protected/controllers/FacilityController.php
<?php

class FacilityController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions{
                'actions' => array('create', 'createstaff', 'update', 'admin', 'delete', 'ChangeStatus', 'main','settings' ,'staff' , 'workinghour'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array(),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }
    
    public function actionWorkinghour(){
        
        $model = Workinghour::model()->findByAttributes(array('wh_facility_id'=>  Yii::app()->user->getState('facility')));

        if(empty($model)){
            $model = new Workinghour;
            $model->weekday['monday']['status'] = TRUE;
            $model->weekday['tuesday']['status'] = TRUE;
            $model->weekday['wednesday']['status'] = TRUE;
            $model->weekday['monday']['status'] = TRUE;
            $model->weekday['thursday']['status'] = TRUE;
            $model->weekday['friday']['status'] = TRUE;
            $model->weekday['saturday']['status'] = TRUE;
            $model->weekday['sunday']['status'] = TRUE;
        }else{
            
            $model->weekday = unserialize($model->wh_facility_data);
            
        }    

        if(isset($_POST['Workinghour'])){
            
            $model->weekday = $_POST['Workinghour']['weekday'];
            $attributes = array('wh_facility_id'=>  Yii::app()->user->getState('facility'));
            $count = Workinghour::model()->countByAttributes($attributes);
            $model->weekday = serialize($model->weekday);
            if($count != 0){
            
                $condition = 'wh_facility_id = '. Yii::app()->user->getState('facility');
                try{
                    Workinghour::model()->updateAll(array('wh_facility_data'=> $model->weekday), $condition);
                    $this->redirect(array('facility/workinghour'));
                }  catch (Exception $e){
                    echo $e->getMessage();
                    exit;
                }
                
                
                
            }else{
                
                $save_model= new Workinghour();
                $save_model->wh_facility_id= Yii::app()->user->getState('facility');
                $save_model->wh_facility_data= $model->weekday;
                if($save_model->save()){
                    Yii::app()->user->setFlash('success', '<strong>Well done!</strong> working hours has been updated successfully!');
                    $this->redirect(array('site/dashboard'));
                }
                
            }
            
        }
        
        
        
//        echo "<pre>";
//        print_r($model->weekday);
//        exit;
        
        
        $this->render('workinghour', array(
            'model' => $model,
            //'staff_model' => $staff_model,
        ));
        
    }


    public function actionstaff(){
        
        $model = new FcUser('search');
        
        $staff_model = new User('settings');

        $model->unsetAttributes();  // clear any default values
        $model->fu_facility_id = Yii::app()->user->getState('facility');
        
        if (isset($_GET['FcUser']))
            $model->attributes = $_GET['FcUser'];

        
        $this->render('staff', array(
            'model' => $model,
            'staff_model' => $staff_model,
        ));
        
    }
    
    
    public function actionsettings(){
        
        
        $model = $this->loadModel(Yii::app()->user->getState('facility'));
        $model->scenario = 'settings';
        
        if(isset($_POST['Facility'])){
            
            $model->attributes = $_POST['Facility'];    
            
            if($model->validate()){
                
                if($model->save(false)){
                    
                    Yii::app()->user->setFlash('success', '<strong>Well done!</strong> Facility settings has been updated successfully!');
                    $this->redirect(array('site/dashboard'));
                    
                }
            }
            
        }
        
        $this->render('settings', array(
            'model' => $model,
        ));
      
        
        
        
    }

    public function actionMain($id) {

        $model = $this->loadModel($id);
        
        if($model->fac_setup){
            Yii::app()->user->setState('facility' , $id);
            $this->redirect(array('site/dashboard'));
            
        }
        
        $model->scenario = 'setup';
        
        $user_model = User::model()->findByAttributes(array('usr_id'=> Yii::app()->user->id));
        $user_model->scenario = 'setup';
        
        $new_user = new User('newuser');
        
        $service = new Services();
        
        
        if(isset($_POST['Facility']) && !empty($_POST['Facility'])){
            
            $model->attributes = $_POST['Facility'];
            
            $user_model->attributes = $_POST['User'];
            
            if($model->validate() && $user_model->validate()){
                
                if($model->save() && $user_model->save()){
                    
                    if(!empty($user_model->usr_lname) && !empty($user_model->usr_email)){
                        
                        $new_user = new User('newuser');
                        
                        $new_user->usr_fname = $user_model->usr_lname;
                        $new_user->usr_email = $_POST['User']['usr_email1'];
                        $new_user->usr_type  = $user_model->usr_type;
                        $password = Utility::getToken(8);
                        $new_user->usr_password = $new_user->hashPassword($password);
                        $new_user->usr_original_password = $password;
                        
                        if($new_user->save(false)){
                            
                            $fc_user = new FcUser();
                            
                            $fc_user->fu_facility_id = $id;
                            $fc_user->fu_user_id = $new_user->usr_id;
                            
                            $fc_user->save(false);
                            
                            
                        }
                        
                    }
                    
                    if(isset($_POST['Services']) && !empty($_POST['Services']['ser_name'])){
                        
                        $service_model = new Services();
                        $service_model = $_POST['Services'];
                        $service_model->ser_fac_id = $id;
                        
                        $service->save(false);
                    }
                    
                    $attributes = array('fac_setup'=>'1');
                    Facility::model()->updateByPk($id, $attributes);
                    Yii::app()->user->setFlash('success', '<strong>Well done!</strong> Facility settings has been updated successfully!');
                    $this->redirect(array('admin'));
                    
                    
                    
                }
            }
            $user_model->validate();
            
            
        }

        $this->render('main', array(
            'model' => $model,
            'user_model'=>$user_model,
            'new_user'=>$new_user,
            'service'=>$service
        ));
    }

    public function actionChangeStatus($id) {
        $model = $this->loadModel($id);

        if ($model->fac_status == '1') {
            $status = '0';
        } else {
            $status = '1';
        }

        $model->fac_status = $status;

        $model->saveAttributes(array('fac_status'));

        Yii::app()->end();
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {

        $model = new Facility('create');

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if (isset($_POST['Facility'])) {
            $model->attributes = $_POST['Facility'];
            if ($model->validate()) {
                $model->fac_usr_id = Yii::app()->user->id;
                $model->save(false);
                Yii::app()->user->setFlash('success', '<strong>Well done!</strong> Facility has been created successfully.');
                if (Yii::app()->request->isAjaxRequest) {
                    $msg = '';

protected/views/facility/_form.php
<?php
/* @var $this FacilityController */
/* @var $model Facility */
/* @var $form CActiveForm */
?>
<div class="form">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'facility-form',
        'action' => Yii::app()->createAbsoluteUrl('facility/create'),
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        //  'afterSubmit'=>'js:yiiFix.ajaxSubmit.afterValidate'
        )
    ));
    ?>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <div class="form-group col-lg-12 clear">
            <?php echo $form->labelEx($model, 'fac_name'); ?>
            <?php echo $form->textField($model, 'fac_name', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <?php echo $form->error($model, 'fac_name'); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-lg-6 clear" style="margin-top: 25px;">
            <?php
            //  FB::setEnabled('false');
            //  echo  CHtml::submitButton($model->isNewRecord ? 'Submit' : 'Save');
            echo CHtml::ajaxSubmitButton($model->isNewRecord ? 'Create' : 'Save', $this->createUrl('facility/create'), array('type' => 'POST',
                'success' => 'function(data) {
                                 var response= jQuery.parseJSON(data);
                                 if (response.success ==true){
                                 //alert(response.div);
                                 $("#statusMsg").html("");
                                 $("#statusMsg").append(response.div);
                                 $("#statusMsg").show().delay(3000).hide(0);
                                 $("#facility-form")[0].reset();
                                 update_grid_view();
                                 $("#myModal").modal("toggle");
                                 return false;
                                 }else{
                                 data = JSON.parse(data);
                                      $.each(data, function(key, val) {
                        $("#facility-form #"+key+"_em_").text(val);                                                    
                        $("#facility-form #"+key+"_em_").show();
                        });      
                                     }

                                 }' //success
                    ), array('type' => 'submit', 'class' => 'btn btn-primary')
            );
            ?>
            
            <a href="#" onclick='$("#myModal").modal("toggle");' >Close</a>
            
        </div>

    </div>    


    <?php $this->endWidget(); ?>

</div><!-- form -->

<script type="text/javascript">
    $('#Facility_fac_to_timing').timepicker();
    $('#Facility_fac_from_timing').timepicker();
    
</script> 

protected/views/facility/_search.php
<?php
/* @var $this FacilityController */
/* @var $model Facility */
/* @var $form CActiveForm */
?>

<div class="wide form">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'action' => Yii::app()->createUrl($this->route),
        'method' => 'get',
    ));
    ?>

    <div class="form-group col-lg-3">
<?php echo $form->label($model, 'fac_name'); ?>
<?php echo $form->textField($model, 'fac_name', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
    </div>

    <div class="row buttons form-group">

    <?php echo CHtml::submitButton('Search', array('class' => 'btn btn-primary searchbutton')); ?>
        
    </div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/facility/admin.php
<?php
/* @var $this FacilityController */
/* @var $model Facility */

$this->breadcrumbs = array(
    'Facilities'
);


Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-f').toggle();
	return false;
});
$('.search-f form').submit(function(){
	$('#facility-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
function update_grid_view()
{
	$('#facility-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
}
");
?>
<div id="statusMsg">    
    <?php
    foreach (Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="alert alert-' . $key . '">'
        . '<button type="button" class="close" data-dismiss="alert">×</button>'
        . $message . "</div>\n";
    }
    ?>    
</div>
<?php
Yii::app()->clientScript->registerScript(
        'flashMassageEffect', '$("#statusMsg").animate({opacity: 1.0}, ' . Yii::app()->params["flasMsgTimeOut"] . ').fadeOut("slow");', CClientScript::POS_READY
);
?>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade in " >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
                <h4 id="myModalLabel" class="modal-title">Add Facility</h4>
            </div>
            <div class="modal-body">
                <?php
                $this->renderPartial('_form', array(
                    'model' => $create_model,
                ));
                ?>
            </div>
        </div>
    </div>
</div>
<div class="row">

    <div class="col-md-10 col-lg-offset-1" >
        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Facility </h4>
                <div class="panel-control">
                    <a href="#" class="btn btn-success btn btn-primary" data-target="#myModal" data-toggle="modal" ><i class="fa fa-plus"></i> Add Facility </a>
                </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <?php
                    $this->widget('zii.widgets.grid.CGridView', array(
                        'id' => 'facility-grid',
                        'dataProvider' => $model->search(),
                        'itemsCssClass' => 'table table-hover table-striped',
                        'template' => "{items}\n{summary}{pager}",
                        //'filter' => $model,
                        'columns' => array(
                            array(
                                'name'=>'fac_name',
                                'type'=>'raw',
                                'value' => 'CHtml::link($data->fac_name,Yii::app()->createUrl("facility/main",array("id"=>$data->fac_id)))',
                            ),
//                            'fac_name',
//                            'fac_address',
//                            'fac_city',
//                            'fac_state',
//                            array(
//                                'name' => 'fac_status',
//                                'value' => '$data->displayStatus()',
//                                'type' => 'raw',
//                                'htmlOptions' => array('width' => '8%', 'style' => 'text-align:center;'),
//                                'headerHtmlOptions' => array('width' => '8%', 'style' => 'text-align:center;'),
//                            ),
                            array(
                                'header' => 'Actions',
                                'class' => 'CButtonColumn',
                                'template' => '{delete}',
                                'htmlOptions' => array('width' => '3%'),
                                'deleteConfirmation' => Yii::t('warnings', 'Are you sure you want to delete this Facility?'),
                                'afterDelete' => 'function(link,success,data){$("#statusMsg").html(data).show();}',
                                'buttons' => array(
                                    'delete' => array(
                                        'label' => Yii::t('common', '<i class="fa fa-remove"></i> '),
                                        'url' => 'Yii::app()->createUrl("/facility/delete",array("id"=>$data["fac_id"]))',
                                        'options' => array('class' => 'btn btn-danger', 'title' => 'Delete'),
                                        'imageUrl' => false,
                                    ),
                                ),
                            ),
                        ),
                    ));
                    ?>
                </div>
            </div>
        </div>

    </div>
</div> 

protected/views/facility/create.php
<?php
/* @var $this FacilityController */
/* @var $model Facility */

$this->breadcrumbs=array(
	'Facilities'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Facility', 'url'=>array('index')),
	array('label'=>'Manage Facility', 'url'=>array('admin')),
);
?>

<h1>Create Facility</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/facility/index.php
<?php
/* @var $this FacilityController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Facilities',
);

$this->menu=array(
	array('label'=>'Create Facility', 'url'=>array('create')),
	array('label'=>'Manage Facility', 'url'=>array('admin')),
);
?>

<h1>Facilities</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/facility/staff.php
<?php
/* @var $this FacilityController */
/* @var $model Facility */

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-f').toggle();
	return false;
});
$('.search-f form').submit(function(){
	$('#facility-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
function update_grid_view()
{
	$('#facility-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
}
");
?>
<div id="statusMsg">    
    <?php
    foreach (Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="alert alert-' . $key . '">'
        . '<button type="button" class="close" data-dismiss="alert">×</button>'
        . $message . "</div>\n";
    }
    ?>    
</div>
<?php
Yii::app()->clientScript->registerScript(
        'flashMassageEffect', '$("#statusMsg").animate({opacity: 1.0}, ' . Yii::app()->params["flasMsgTimeOut"] . ').fadeOut("slow");', CClientScript::POS_READY
);
?>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade in " >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
                <h4 id="myModalLabel" class="modal-title">Add Staff</h4>
            </div>
            <div class="modal-body">
                <?php
                $this->renderPartial('_staffform', array(
                    'model' => $staff_model,
                ));
                ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-lg-offset-1" >
        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Facility </h4>
                <div class="panel-control">
                    <a href="#" class="btn btn-success btn btn-primary" data-target="#myModal" data-toggle="modal" ><i class="fa fa-plus"></i> Add Staff </a>
                </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <?php
                    $this->widget('zii.widgets.grid.CGridView', array(
                        'id' => 'facility-grid',
                        'dataProvider' => $model->search(),
                        'itemsCssClass' => 'table table-hover table-striped',
                        'template' => "{items}\n{summary}{pager}",
                        //'filter' => $model,
                        'columns' => array(
                            array(
                                'name'=>'fu_user_id',
                                'value'=>'$data->FcaUser->usr_fname',
                                //'type'=>'raw',
                                //'value' => 'CHtml::link($data->fac_name,Yii::app()->createUrl("facility/main",array("id"=>$data->fac_id)))',
                            ),
//                            'fac_name',
//                            'fac_address',
//                            'fac_city',
//                            'fac_state',
//                            array(
//                                'name' => 'fac_status',
//                                'value' => '$data->displayStatus()',
//                                'type' => 'raw',
//                                'htmlOptions' => array('width' => '8%', 'style' => 'text-align:center;'),
//                                'headerHtmlOptions' => array('width' => '8%', 'style' => 'text-align:center;'),
//                            ),
                            array(
                                'header' => 'Actions',
                                'class' => 'CButtonColumn',
                                'template' => '{delete}',
                                'htmlOptions' => array('width' => '3%'),
                                'deleteConfirmation' => Yii::t('warnings', 'Are you sure you want to delete this User?'),
                                'afterDelete' => 'function(link,success,data){$("#statusMsg").html(data).show();}',
                                'buttons' => array(
                                    'delete' => array(
                                        'label' => Yii::t('common', '<i class="fa fa-remove"></i> '),
                                        'url' => 'Yii::app()->createUrl("/user/delete",array("id"=>$data["fu_id"]))',
                                        'options' => array('class' => 'btn btn-danger', 'title' => 'Delete'),
                                        'imageUrl' => false,
                                    ),
                                ),
                            ),
                        ),
                    ));
                    ?>
                </div>
            </div>
        </div>

    </div>
</div> 